(function() {var implementors = {};
implementors["redis"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"redis/async/struct.SharedConnection.html\" title=\"struct redis::async::SharedConnection\">SharedConnection</a>",synthetic:false,types:["redis::async::SharedConnection"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"redis/struct.Client.html\" title=\"struct redis::Client\">Client</a>",synthetic:false,types:["redis::client::Client"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"redis/struct.Cmd.html\" title=\"struct redis::Cmd\">Cmd</a>",synthetic:false,types:["redis::cmd::Cmd"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"redis/enum.ConnectionAddr.html\" title=\"enum redis::ConnectionAddr\">ConnectionAddr</a>",synthetic:false,types:["redis::connection::ConnectionAddr"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"redis/struct.ConnectionInfo.html\" title=\"struct redis::ConnectionInfo\">ConnectionInfo</a>",synthetic:false,types:["redis::connection::ConnectionInfo"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"redis/enum.NumericBehavior.html\" title=\"enum redis::NumericBehavior\">NumericBehavior</a>",synthetic:false,types:["redis::types::NumericBehavior"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"redis/enum.ErrorKind.html\" title=\"enum redis::ErrorKind\">ErrorKind</a>",synthetic:false,types:["redis::types::ErrorKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"redis/enum.Value.html\" title=\"enum redis::Value\">Value</a>",synthetic:false,types:["redis::types::Value"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
